import Link from 'next/link'
import QuoteEngine from '@/components/QuoteEngine'
import { ServiceHeroVisual } from '@/components/VisualSystems'
import { CONTACT } from '@/lib/neartec-data'
export const metadata = { title: 'CRM y automatización NearTec', description: 'Organiza prospectos, seguimientos y respuestas con CRM, automatización y WhatsApp conectados.' }
export default function Page(){ return <>
<section className="page-hero page-hero-v41"><div className="container page-hero-grid"><div><span className="eyebrow eyebrow-solid">CRM y automatización</span><h1>Responder mejor también vende más.</h1><p>Ordenamos tus prospectos, seguimientos y mensajes para que cada oportunidad reciba atención a tiempo y tu equipo tenga más control del proceso comercial.</p><div className="hero-actions"><Link className="btn btn-green" href="/cotizador">Quiero cotizar</Link><Link className="btn btn-outline" href="/landing">Quiero diagnóstico</Link><a className="btn btn-ghost" href={`https://wa.me/${CONTACT.whatsappNumber}`}>WhatsApp</a></div></div><ServiceHeroVisual kind="crm"/></div></section>
<section className="section section-separated"><div className="container feature-grid"><div className="feature-tile"><span>01</span><b>Organiza tus prospectos</b><p>Clasificamos contactos por intención, tamaño, necesidad o urgencia para atender mejor.</p></div><div className="feature-tile"><span>02</span><b>Da seguimiento sin olvidar oportunidades</b><p>Automatizamos recordatorios, rutas y respuestas para reducir fugas comerciales.</p></div><div className="feature-tile"><span>03</span><b>Conecta canales clave</b><p>Integramos formularios, WhatsApp, correo y herramientas de seguimiento para una atención más sólida.</p></div></div></section>
<section className="section-tight"><div className="container"><QuoteEngine compact/></div></section></> }
