import Link from 'next/link'
import QuoteEngine from '@/components/QuoteEngine'
import { SolutionVisual } from '@/components/VisualSystems'
import { CONTACT } from '@/lib/neartec-data'
export const metadata = { title: 'Sitios web y landings NearTec', description: 'Creamos sitios web y landing pages enfocadas en explicar mejor tu oferta y convertir visitas en contactos.' }
export default function Page(){ return <>
<section className="page-hero page-hero-v41"><div className="container page-hero-grid"><div><span className="eyebrow eyebrow-solid">Diseño web NearTec</span><h1>Tu sitio debe ayudarte a vender, no solo verse bien.</h1><p>Diseñamos páginas rápidas, claras y listas para pauta, SEO y WhatsApp, para que más personas entiendan tu propuesta y se animen a contactarte.</p><div className="hero-actions"><Link className="btn btn-green" href="/cotizador">Quiero cotizar</Link><Link className="btn btn-outline" href="/landing">Quiero diagnóstico</Link><a className="btn btn-ghost" href={`https://wa.me/${CONTACT.whatsappNumber}`}>WhatsApp</a></div></div><SolutionVisual kind="web"/></div></section>
<section className="section section-separated"><div className="container feature-grid"><div className="feature-tile"><span>01</span><b>Explica mejor lo que vendes</b><p>Reducimos la confusión con mensajes claros, jerarquía visual y llamadas a la acción bien pensadas.</p></div><div className="feature-tile"><span>02</span><b>Convierte visitas en contactos</b><p>Con formularios, CTA y rutas directas hacia WhatsApp, correo o cotización.</p></div><div className="feature-tile"><span>03</span><b>Lista para crecer</b><p>Con SEO técnico, buena velocidad y estructura preparada para campañas y posicionamiento.</p></div></div></section>
<section className="section-tight"><div className="container"><QuoteEngine compact/></div></section></> }
