import Link from 'next/link'
import QuoteEngine from '@/components/QuoteEngine'
import { SolutionVisual } from '@/components/VisualSystems'
import { CONTACT } from '@/lib/neartec-data'
export const metadata = { title: 'CompuNegocio NearTec', description: 'Impulsa tu operación con CompuNegocio: ventas, inventario, usuarios y timbres con una base clara.' }
export default function Page(){ return <>
<section className="page-hero page-hero-v41"><div className="container page-hero-grid"><div><span className="eyebrow eyebrow-solid">CompuNegocio</span><h1>Vende, cobra y controla mejor tu operación diaria.</h1><p>NearTec te ayuda a implementar CompuNegocio para que tengas más orden en ventas, inventario, usuarios y timbres, con una base clara para crecer con menos fricción.</p><div className="hero-actions"><Link className="btn btn-green" href="/cotizador">Quiero cotizar</Link><Link className="btn btn-outline" href="/landing">Quiero diagnóstico</Link><a className="btn btn-ghost" href={`https://wa.me/${CONTACT.whatsappNumber}`}>WhatsApp</a></div></div><SolutionVisual kind="compunegocio"/></div></section>
<section className="section section-separated"><div className="container feature-grid"><div className="feature-tile"><span>01</span><b>Licencias según tu tamaño</b><p>Te orientamos con precios base documentados por estación para que sepas cómo empezar.</p></div><div className="feature-tile"><span>02</span><b>Implementación más simple</b><p>Te ayudamos a configurar la herramienta para que se integre mejor a tu operación.</p></div><div className="feature-tile"><span>03</span><b>Timbres y operación listos para cotizar</b><p>Calcula lo necesario para comenzar con una base más clara y tomar decisiones sin adivinar.</p></div></div></section>
<section className="section-tight"><div className="container"><QuoteEngine compact/></div></section></> }
